### ISSUE TITLE
How to implement pGrid As required ?!

### ISSUE THREAD

**Issue by Indianagrenoble** [syssi/homeassistant-goecharger-mqtt#108]
Dear @syssi Sebastian,

First I would like thanks a lot about your Go-e Charger implement in HAOS : It's works fine and it's beautifull and helpfull !

I'm not an software programer and It's hard to understand **how to** implement my **_pGrid_** frome my ESS Victron Energy MULTIPLUS 2 battery inverter... 

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/57313381/21b96bb7-6e76-4ef2-852d-bbd65e3af111)

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/57313381/942b8658-6947-4e5a-a151-5d2e87b87173)

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/57313381/5de406c7-619b-471a-bf52-ed587350d107)

I have well my sensor called 'sensor.victron_grid_load' but I don't understand how to put it inside your code pgrid, pakku and ppv sensors ?!

Could you help me please ?! 

Best Regards

Alexandre (french guy)

**Comment by Indianagrenoble** [comment]
Ho ho !!
I have done it !

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/57313381/056bb57f-f4ac-4ea8-ba33-afba33c86f81)


for others :

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/57313381/9010081b-ede8-4a22-9929-0e6f6756af7e)

**Comment by Indianagrenoble** [comment]
![RTFM](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/57313381/853e2542-0a60-45c4-8bcc-83b874dd92aa)

**Comment by syssi** [comment]
Good job! Let's close this issue. :-)
