### ISSUE TITLE
Entity sensor.go_echarger_XXXXXX_wh has state class total_increasing, but its state is not strictly increasing

### ISSUE THREAD

**Issue by tomik671108** [syssi/homeassistant-goecharger-mqtt#109]
Hi.
Recently I've been getting this warning in my logs:

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:405
Integration: Sensor (documentation, issues)
First occurred: 15:05:10 (1 occurrences)
Last logged: 15:05:10

Entity sensor.go_echarger_xxxxxx_wh from integration goecharger_mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 0.044042 (0.047654) with last_updated set to 2023-08-31T13:01:18.267895+00:00. Please report it to the custom integration author.

Is it serious ?.

**Comment by mikak** [comment]
I have seen this too. In the end of charging when battery is full, at some times the power flow may be reversed (from car to system) and thus total energy is not strictly increasing. Not serious as the flow is minimal.
