### ISSUE TITLE
How to add a second go-e Charger?

### ISSUE THREAD

**Issue by MB1983k** [syssi/homeassistant-goecharger-mqtt#115]
I am unfortunately not able to add a second go-e charger due to the following issue:
Platform goecharger does not generate unique IDs.

How could I solve the problem?

**Comment by syssi** [comment]
Are you sure you are using this custom component because a unique ID is generated in general here.

**Comment by MB1983k** [comment]
Yes - I was directly referred from the home assistant page when clicking in "documentation"...

**Comment by syssi** [comment]
Interesting. I will have a look! :-)

**Comment by MB1983k** [comment]
Many thanks - if you need further information please let me know. In the meantime I try to start the complete setup again... maybe I had some issues in my setup process

**Comment by MB1983k** [comment]
Is there something specific I need to include in the field "base topic"? Is there any specific format needed for the serial number?

**Comment by syssi** [comment]
First of all you should be able to add the component multiple times to talk to different chargers. IMO a missing `unique ID` shouldn't have an impact here.

The `base_topic` depends on your charger version & firmware. This is the expected pattern to be able to auto-discover your devices: https://github.com/syssi/homeassistant-goecharger-mqtt/blob/main/custom_components/goecharger_mqtt/config_flow.py#L79-L82

**Comment by MB1983k** [comment]
ok... to be honest - I do not know what to do with this (sorry!).
I am even not able anymore to add again the first go-e charger which worked before... And I think it was auto detected before. I also know from the MQTT Explorer that both send their values correctly to the Mosquitto broker...

**Comment by MB1983k** [comment]
first device is running again after using my backup... but second one is not discovered and I do not really understand what to do or where I could find helpful instructions...

**Comment by syssi** [comment]
Could you try to subscribe to your mosquitto broker and provide some received messages (including the topics) of both devices? Do you know how to monitor the MQTT traffic manually?

**Comment by MB1983k** [comment]
I am able to see all the details send using MQTT Explorer, but I do not know how to monitor it using the Mosquitto broker. Anyway the MQTT is connected to the Mosquitto broker and should therefore show all data

**Comment by MB1983k** [comment]
Based on the Mosquitto broker the Base topic seems to be go-eCharger/233782/

Anyway I am not able to get it running using the integration. But when monitoring the MQTT Explorer all information are correctly forwarded to the Mosquitto broker. Both go-e Chargers are identical.... same firmware etc. The other one is running without any issues...

**Comment by syssi** [comment]
Could you tell me the base topic of the working one? Does it start with a `/` or not?

**Comment by MB1983k** [comment]
without a /

but I tried to setup the go-e Charger with several combinations for the base topic considering with / and without

**Comment by MB1983k** [comment]
now it worked ;-)

After a high amount of restarts and even shutting down the system I was able to have it running now... for the base topic I just have included "go-eCharger" and with the serial number it resulted in an autodetect ;-)...

Many thanks for your support!
