### ISSUE TITLE
Default mqtt topic

### ISSUE THREAD

**Issue by ChristianDresel** [syssi/homeassistant-goecharger-mqtt#116]
Hi

i had some problemes to connect the go-e to home assistant. The biggest problem, the go-e has as default mqtt topic go-eCharger/ID but the default from Home Assistant is /go-eCharger/ID and nothing works. It works after i change the topic in hass to go-eCharger/ID

Wallbox is 22kw with Firmware 055.7

best regards
Christian

**Comment by michaelhagg** [comment]
Hi
how did you do this?

**Comment by Sebbo69** [comment]
Same here. But I changed it in GoE APP / Internet -> Erweiterte Einstellungen -> MQTT API Prefix

Add a "/" at the begin

**Comment by syssi** [comment]
Is this still an issue?
