### ISSUE TITLE
Set awpl?

### ISSUE THREAD

**Issue by kalaws** [syssi/homeassistant-goecharger-mqtt#120]
Is there any way to set `awpl`? Would be exceedingly useful.

**Comment by syssi** [comment]
Could you describe in detail what you are looking for? May be it's easier to start/stop charging depending on an external retrieved price instead of passing prices to the charger firmware.

**Comment by kalaws** [comment]
I’m currently automating smart charging based on prices through home assistant. I’ve set up a price sensor which is using import prices most of they day, but export prices between for example 10-16, when a pv surplus is likely. It is like a basic manual form of forecasting. But the automations sometimes fail, and either way add an extra layer. If I could just pass on my proprietary price list to the charger and let it handle the starting and stopping, I think that would simplify the whole setup.

**Comment by kalaws** [comment]
Part of the point of this kind of forecasting is to account for the fact that sometimes it is more beneficial to not charge when there is a pv surplus but instead export during the day and charge during night.

**Comment by syssi** [comment]
Could you ask the manufacturer about passing pricelists using `awpl`? I assume it's read-only at the moment and populated using internal retrieval methods.

**Comment by kalaws** [comment]
[Tried](https://github.com/goecharger/go-eCharger-API-v2/discussions/174) some time back, no response so far.

**Comment by syssi** [comment]
There is no room for improvements here unfortunately. Let's close this issue for now. Feel free to create a new issue or re-open this one if the situation / features of the firmware has changed.
