### ISSUE TITLE
PV Surplus Charging - what happens when pGrid gets "unavailable"?

### ISSUE THREAD

**Issue by parkflyer** [syssi/homeassistant-goecharger-mqtt#125]
My MQTT based grid sensor is WLAN based and there is the possibility that the "Power Saldo" which I use for pGrid in the "PV Surplus Charging" automation could get unavailable (e. g. no data received for 60 sec due to WLAN problems). What will then happen to the charging process?

Cheers,
parkflyer

**Comment by OhneNik** [comment]
Hey, 

just do the good old |float(0) template. 

{{ “unavailable”|float(0) }} returns the default 0 in the template. 

I think what really happens is, that the go-e does not accept the input and ignores the value.

**Comment by OhneNik** [comment]
Yep all templating functionality is working there. 

But if you like to alter the pGrid values on multiple heuristics I‘d prefer doing something like [this ](https://github.com/syssi/homeassistant-goecharger-mqtt/issues/101#issuecomment-1541894260)

**Comment by syssi** [comment]
Let's close this issue. It looks like it's resolved.
