### ISSUE TITLE
Is it possible to manually set the load balancing priority in HA?

### ISSUE THREAD

**Issue by MB1983k** [syssi/homeassistant-goecharger-mqtt#131]
I would like to manually change the load balancing priority based on which car should be priorized. Unfortunately I even do not see the priority in HA - is there a chance to include this?

**Comment by syssi** [comment]
Do you know the API key you are asking for?

**Comment by MB1983k** [comment]
Seems like „lop“… at least this one is changing when I change the priority value in the app

**Comment by syssi** [comment]
It looks like you are on the right track:

![lop](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/2735933/d8a920ed-b1a9-46b2-8304-a6889e074c08)

Could you try to provide the possible/allowed values for `lot`?

**Comment by MB1983k** [comment]
It is 1 through 99 based on the app

**Comment by syssi** [comment]
I've extended the integration by a new `number` entity (disabled per default. Must be enabled explicit). See #132.

There are some bad news too: It looks like the API key `lop` isn't available via MQTT right now. Please give it a try nevertheless but there is the risk this feature isn't available via MQTT at the moment (but could be in future).

**Comment by MB1983k** [comment]
Stupid question - how can I enable it???
