### ISSUE TITLE
No credentials for broker connection

### ISSUE THREAD

**Issue by rbiegel** [syssi/homeassistant-goecharger-mqtt#139]
Is it possible to set user, password and certificates for the connection to the broker? If yes, where? If no, is it planned to be supported in the future?

Thanks in advance!

**Comment by syssi** [comment]
This integration requires/uses the `mqtt` integration to talk to the broker. It looks like the `mqtt` integration supports these settings already: https://www.home-assistant.io/integrations/mqtt/

**Comment by syssi** [comment]
In other words: You have to setup the `mqtt` integration first and add these integration as second step.
