### ISSUE TITLE
Working with Gemini flex? 

### ISSUE THREAD

**Issue by myxor** [syssi/homeassistant-goecharger-mqtt#144]
Is this working with go-e Charger Gemini Flex (https://go-e.com/en/products/go-e-charger-gemini-flex)?

**Comment by K3vb3rt** [comment]
Sure, it’s same hardware as the normal one. Just the connection is FLEXible and nox FIXed.

**Comment by myxor** [comment]
Thank you, i asked because the README just talks about the HOME+ and HOMEfix models.
