### ISSUE TITLE
Separate current meter needed? 

### ISSUE THREAD

**Issue by vb-git** [syssi/homeassistant-goecharger-mqtt#147]
My charger is on its way to me, but now I wonder if I also need to buy a separate current meter (like a Shelly) if I want to know the live current/power per phase?

I see there are sensors for the current and power per phase, but are these displaying actual "live" measured values a separate meter would also provide, or do they display just the numbers matching for the currently set charge current limit. And do these values update every few seconds or slower?

If the charger already provides these values I won't have to spend extra for a separate 3 phase current meter :-)

**Comment by syssi** [comment]
The charger is able to measure its own power consumption. If you want to know the total power consumption / imported energy from the grid another measurement device (f.e. smartmeter) is required. There are a lot of people which tries to feed PV surplus energy (if available) into the car battery.

**Comment by vb-git** [comment]
Thanks, this is good news! I already have a smart grid meter with production/consumption readout and i can read out the total PV production, so then i have all the ingredients needed to charge smart and i don't need a separate coil amp meter for the charger. This is a real advantage of the go-e charger which i did not find on the go-e website! This was not really an issue but more a question, but i hope it will help other people also.
