### ISSUE TITLE
Updating state for sensor.go_echarger_0XXXXXX_nrg_8 took 0.671 seconds

### ISSUE THREAD

**Issue by showupch** [syssi/homeassistant-goecharger-mqtt#151]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1183
First occurred: 04:32:25 (1 occurrences)
Last logged: 04:32:25

Updating state for sensor.go_echarger_0XXXXXX_nrg_8 (<class 'custom_components.goecharger_mqtt.sensor.GoEChargerSensor'>) took 0.671 seconds. Please create a bug report at https://github.com/syssi/homeassistant-goecharger-mqtt/issues

**Comment by syssi** [comment]
Hmmm.. updating this sensor state doesn't involve any computation. Could you provide some details about your host / hardware? It looks like your host isn't powerful enough to handle all the work in general.

**Comment by showupch** [comment]
pi4 8gb
core 2024.5.5
supervisor 2024.05.1
Op. system 12.3
Front end  20240501.1

**Comment by showupch** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1183
First occurred: 20:04:15 (1 occurrences)
Last logged: 20:04:15

Updating state for sensor.go_echarger_0XXXXXX_nrg_5 (<class 'custom_components.goecharger_mqtt.sensor.GoEChargerSensor'>) took 0.558 seconds. Please create a bug report at https://github.com/syssi/homeassistant-goecharger-mqtt/issues

**Comment by showupch** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1183
First occurred: 7:33:24 PM (1 occurrences)
Last logged: 7:33:24 PM

Updating state for sensor.go_echarger_0XXXXXX_nrg_5 (<class 'custom_components.goecharger_mqtt.sensor.GoEChargerSensor'>) took 0.552 seconds. Please create a bug report at https://github.com/syssi/homeassistant-goecharger-mqtt/issues

**Comment by syssi** [comment]
It looks like your Raspberry Pi isn't powerful enough to handle all tasks in time. This issue cannot be resolved here.

**Comment by showupch** [comment]
> It looks like your Raspberry Pi isn't powerful enough to handle all tasks in time. This issue cannot be resolved here.

I will setup a Pi5 with 8GB tomorrow. I will let you know asap how it goes.

Thanks.

**Comment by syssi** [comment]
Do you agree to close this issue?

**Comment by showupch** [comment]
> Do you agree to close this issue?

Yes sure. With the Pi5 all is working correct. Thanks
