### ISSUE TITLE
Some entities are not availible, nothing is availible when I change the prefix to /go-eCharger/xxxxx/

### ISSUE THREAD

**Issue by AlphaBrug** [syssi/homeassistant-goecharger-mqtt#170]
Hi all,
Unfortunately, some entities are not available in the view. If I change the prefix to /go-eCharger/xxxxx/, no entities are available at all.
In the MQQT Explorer, however, I can see the values for dwo, awp etc.
![image](https://github.com/user-attachments/assets/7dc19835-87c5-47e6-893a-06637b305988)

<img width="116" alt="image" src="https://github.com/user-attachments/assets/4c9225f1-2eb1-44e5-afb5-6e36361f0c8f">

**Comment by syssi** [comment]
Could you take a look at the developer tools (States: http://<yourhassinstance>/developer-tools/state) and filter/search for "dwo". Do you see multiple entities with the "dwo" suffix?

**Comment by ArendBrugmans** [comment]
No I only see one entity:
<img width="801" alt="image" src="https://github.com/user-attachments/assets/bd8e601d-6790-4c03-8c91-b8ea18e0c50b">

**Comment by AlphaBrug** [comment]
Hi,
The entities are now availible, I reinstalled everything and added the pages via devices --> GoeCharger -->Entities --> Add to dashboard
