### ISSUE TITLE
goe-charger produces negative values

### ISSUE THREAD

**Issue by Kalle2018** [syssi/homeassistant-goecharger-mqtt#172]
Ho can I fix this: 

![2024-09-17 22_49_08-Entwicklerwerkzeuge – Home Assistant – Mozilla Firefox](https://github.com/user-attachments/assets/87a76a58-86b2-4c71-81b7-e2fc1a52fbbb)

![2024-09-17 12_26_13-Entwicklerwerkzeuge – Home Assistant – Mozilla Firefox](https://github.com/user-attachments/assets/cd728b31-4642-41e8-8a28-e38493138669)

**Comment by zinkst** [comment]
I have the same problem. 

Any idea what could be the problem. Is that a problem of the integration or of home-assistant ?

![Bildschirmfoto vom 2024-11-16 19-52-18](https://github.com/user-attachments/assets/9b21b977-f781-4db5-b1ea-eeade0745418)

**Comment by syssi** [comment]
The measurement is passed 1:1 as it gets received from the charger:

https://github.com/syssi/homeassistant-goecharger-mqtt/blob/main/custom_components/goecharger_mqtt/definitions/sensor.py#L1942-L1951

**Comment by Kalle2018** [comment]
Ich antworte mal auf Deutsch, und hoffe das ist ok. 
Welcher Teil von Home Assistant ist denn dafür verantwortlich, die Summe in Wh für jeweils 5 Minuten in der Datenbank abzulegen?

**Comment by syssi** [comment]
Diese Mechanismus des Cores ist dafuer verantwortlich: https://data.home-assistant.io/docs/statistics/

Ob man davon Gebrauch macht entscheidet man über diese Zeile: https://github.com/syssi/homeassistant-goecharger-mqtt/blob/main/custom_components/goecharger_mqtt/definitions/sensor.py#L1948

Hier wird davon ausgegangen, dass der Sensorwert vom Charger eine Art Zaehlerstand ist, welcher sinken und steigen kann: https://developers.home-assistant.io/blog/2021/09/20/state_class_total/

**Comment by Kalle2018** [comment]
Wenn man die Wallbox vom Auto trennt, geht der Wert auf 0, aber man will ja dann in der Statistik keinen Abzug in der Statistik bekommen. Mein Ziel war es jedenfalls, in Home Assistant zu dokumentieren wann ich wieviel Strom ins Auto geladen habe. 
Die Klasse state_class_total scheint mir dann die falsche Wahl zu sein.

**Comment by syssi** [comment]
Gute Idee! `TOTAL_INCREASING` ist die bessere Wahl.

**Comment by Kalle2018** [comment]
Thank you for your support, it is working well.
