### ISSUE TITLE
Extension/Entities get no data

### ISSUE THREAD

**Issue by anton3006** [syssi/homeassistant-goecharger-mqtt#175]
I installed the extension as instructed and configured the mqtt server in the app.  I can see that data is received from mqtt via mqtt explorer but no matter how I configure the extension, there is no data available.

I´m using version 0.25.0 of the extension with an homefix 11kw charger with hardware-version 02

mqtt explorer:
![mqtt](https://github.com/user-attachments/assets/b28cf919-eb8c-4905-b6cb-b8fa06a63376)

I tried a lot of basic topics in the configuration like go-eCharger, go-eCharger/, go-eCharger/xxxxxx, go-eCharger/xxxxxx/, go-eCharger/xxxxxx/status but neither of them works and all entities are unavailable.

Appriciate any help!

**Comment by syssi** [comment]
The leading slash is important. Please try: `/go-eCharger`

**Comment by syssi** [comment]
Please go to the `mqtt` integration:

1. http://<your-hass-instacen>/config/integrations/integration/mqtt
2. Click "configure"
3. Go to the "Listen to a topic" section
4. Use `/go-eCharger` as `topic to suscribe to`
5. Press `Start listening`

Is Home Assistant able to see the traffic too?

**Comment by anton3006** [comment]
yes, thats working as well:
![mqtt](https://github.com/user-attachments/assets/50cbc46f-4302-4d2a-b166-4c5732dd907d)

**Comment by syssi** [comment]
This is traffic of the MQTT API version 1. This component supports API version 2 only.

See https://github.com/syssi/homeassistant-goecharger-mqtt/issues/22

**Comment by anton3006** [comment]
So sorry I missed that. I'll use the suggested inegration there but love to see this one also working with v1
