### ISSUE TITLE
No success in go-e integration

### ISSUE THREAD

**Issue by Fibbefobbe** [syssi/homeassistant-goecharger-mqtt#178]
I try to Connect my Go-e to HA. Unfortunatly ... I don´t have any success. Maybe someone can help me. I  installed everything and I switched on the MQTT in the go-e app. I have the MQTT Integration I made a new user for mqtt. I connected everything and I think, I can See all the Data in the mqtt Explorer, but not in the Integration itself. It says: entity "nicht verfügbar". What am I Doing wrong?

<img width="315" alt="Bildschirmfoto 2024-11-20 um 16 25 14" src="https://github.com/user-attachments/assets/9442b602-da98-47c2-95ea-0dbdfa3bb783">

{"version":"B","tme":"2011241625","rbc":"18","rbt":"72486401","car":"2","amp":"16","amx":"16","err":"0","ast":"0","alw":"1","stp":"0","cbl":"32","pha":"63","tmp":"35","tma":[31.00,26.50,28.63,37.00,81.50,93.75],"amt":"32","dws":"982564","dwo":"0","adi":"1","uby":"0","eto":"56010","wst":"3","txi":"2","nrg":[209,213,214,2,152,0,0,31,0,0,0,321,100,0,5,78],"fwv":"042.0","sse":"041580","wss":"UF-DEV","wke":"********","wen":"1","cdi":"0","tof":"101","tds":"1","lbr":"255","aho":"3","afi":"7","azo":"0","ama":"32","al1":"10","al2":"16","al3":"20","al4":"24","al5":"32","cid":"255","cch":"65535","cfi":"65280","lse":"0","ust":"0","wak":"","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"0","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"04566862","rcr":"5F756256","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"AirTag","rnm":"GoE","rne":"","rn4":"","rn5":"","rn6":"","rn7":"","rn8":"","rn9":"","rn1":"","loe":0,"lot":0,"lod":65535,"lts":0,"lom":0,"lop":0,"log":"","lon":0,"lof":0,"loa":0,"lch":0,"mce":1,"mcs":"10.88.90.177","mcp":1883,"mcu":"mqtt_user ","mck":"nipmavjawd","mcc":1,"pco":"","cmf":0,"ath":1200,"psp":11300,"cco":180,"map":123,"frm":1,"los":"{\"chg\":[[\"053644\",10,0,1,0,[1,2,3],6]]}"}

**Comment by syssi** [comment]
This traffic (API Version 1) is unsupported. See #22

**Comment by Fibbefobbe** [comment]
Oh no! Is there any chance to get data from this go-e in my home assistant?

**Comment by syssi** [comment]
Some go-e chargers does support both API versions. Are you able to enable v2 using the Android App? Which go-e charger version do you own? In general https://github.com/cathiele/homeassistant-goecharger is the way to go for models supporting API version1 only.

**Comment by Fibbefobbe** [comment]
![IMG_2550](https://github.com/user-attachments/assets/07c0c95a-4563-4eda-b0ea-3e46d3c6d0ac)

**Comment by syssi** [comment]
This https://github.com/cathiele/homeassistant-goecharger integration uses the HTTP API. What's the IP address of your go-e charger? Try to open this URL using a browser: http://<goe-charger-ip>/status

Do you see a JSON response?

**Comment by Fibbefobbe** [comment]
<img width="658" alt="Bildschirmfoto 2024-11-20 um 17 55 55" src="https://github.com/user-attachments/assets/a3338e14-f2ca-45a4-9b49-04566a16343c">

**Comment by syssi** [comment]
Are you able to ping you go-e charger?

**Comment by syssi** [comment]
It's important to start with `http://`: http://10.88.90.187/status

**Comment by Fibbefobbe** [comment]
I cannot ping it, I don´t get a response from http://10.88.90.187/status. 
But in my unify it´s online and it has the IP 10.88.90.187. 

![IMG_2552](https://github.com/user-attachments/assets/e6b726a9-60cf-4b49-9ee8-9a8dafeaf784)

![IMG_2553](https://github.com/user-attachments/assets/ce09147e-22f5-4129-b104-9576ba4e6d01)

<img width="469" alt="Bildschirmfoto 2024-11-20 um 18 13 32" src="https://github.com/user-attachments/assets/aca3a63e-608f-40e4-a84a-a9d441ad4445">

**Comment by syssi** [comment]
Are all devices at the same network?

**Comment by Fibbefobbe** [comment]
yes!
and same IP Range

**Comment by syssi** [comment]
That's strange especially cloud and mqtt (outgoing) traffic is working but incoming traffic doesn't work. Did you try to reboot the charger?

**Comment by Fibbefobbe** [comment]
I made a software reboot. no effect. I can switch the power off ... we will see...

**Comment by syssi** [comment]
Let's assume you labeled the wrong device with the name "go-e garage" and we want to proof this. Could you power off your charger and check the device is still associated with your WiFi accesspoint?

**Comment by Fibbefobbe** [comment]
I am so stupid!!! 
I have 2 go-e and I just gave them the wrong name, so I always tried to Connect the wrong one. New, everything is fine.  Thank you very much for your help. The last Tip "_Could you power off your charger and check the device is still associated with your WiFi accesspoint?_" helped me to find out.
