### ISSUE TITLE
Add a restart button entity

### ISSUE THREAD

**Issue by kolossboss** [syssi/homeassistant-goecharger-mqtt#23]
Hi,

thanks for the integration. Works like a charm!

Is it possible to add a button to restart the charger? With Firmware 053.0 there is the ability to do this with an API call `rst=1`.
I need this to start charging the new Renault ZOE (R135) . 
I currently solved this with a command line switch. But its far from perfect....

I hope its possible. Thanks a lot.

**Comment by syssi** [comment]
I will expose an additional entity! For the meantime: There is an undocumented service already called `goecharger_mqtt.set_config_key`. You can use this service to change `key=rst` to `value=1`.

**Comment by kolossboss** [comment]
Thanks a lot. I will try.

**Comment by syssi** [comment]
Do you know the new `sua` command? Is this an alternative to the `rst`?

![sua](https://user-images.githubusercontent.com/2735933/155591806-bab2cc4e-99e9-4c1c-b105-4e1bcd6f1a38.png)

**Comment by kolossboss** [comment]
I think that is the same function what you can set up in the goe.app
Sadly I cant get it to work with the zoe.
But maybe you can add this API key and I can try.

![BB6B1E22-DB90-46AA-BFD6-8B701AF2CD5A](https://user-images.githubusercontent.com/11015086/155593513-a77c0362-a22b-4185-97b2-5586da210dfa.png)
