### ISSUE TITLE
Add `sua` as optimistic switch

### ISSUE THREAD

**Issue by syssi** [syssi/homeassistant-goecharger-mqtt#26]
Optimistic because the current state cannot be retrieved at the moment.

**Comment by syssi** [comment]
@kolossboss

**Comment by syssi** [comment]
I've prepared a new release (`0.5.0`). Please give it a try!

**Comment by kolossboss** [comment]
Thanks for adding this.

Unfortunately it doesn't work for me. Seems to do nothing.
Also the switch "Simulate unplugging" does not trigger in the app.
Not sure what this `sue` key exactly do.
