### ISSUE TITLE
Connection issues.

### ISSUE THREAD

**Issue by JRauff** [syssi/homeassistant-goecharger-mqtt#30]
Hi.
This is probably a NOOB issue. ;)

I can't get my charger to connect with my Home-assistant mqqt server, its working fine with my sonoff. I think the problem is in my goecharge app mqtt setup, what exactly should i type in the 'url' to get a connection? :)
I thought it was my mqttuser:mqttpass@HAip:mqttport ?
If i add manual in itegrations, it says its added successfully, but no feedback from charger.
-hopefully its me who's wrong ;)

**Comment by syssi** [comment]
I cannot share a screenshot because it contains my password. ;-)

This is the expected value at the go-e app:

```
mqtt://username:password@ipaddress:port
```

f.e.

````
mqtt://max:secret123@192.168.132.1:1883`

**Comment by JRauff** [comment]
Thank you, i have to figure out whats wrong. 👍🏻
