### ISSUE TITLE
Please make acs writable

### ISSUE THREAD

**Issue by kolossboss** [syssi/homeassistant-goecharger-mqtt#34]
Hi,

to optimize my PV - charging control, I need a way, to disallow automatic charge start, when plugging in the charging plug.

Maybe you can make this key writable?
<html>
<body>

acs | R/W | uint8 | Config | access_control user setting (Open=0, Wait=1)
-- | -- | -- | -- | --

Thanks a lot.

**Comment by syssi** [comment]
Are you sure this is the correct key you are looking for? Could you explain the meaning of `Open` and `Wait`?

**Comment by kolossboss** [comment]
I think its the key to enable / disable access control with RFID - Chip.

I think its possible to prevent auto charge start when its set to `wait` (Access Key needed)

**Comment by syssi** [comment]
I've released a new version. Please give it a try!

**Comment by kolossboss** [comment]
Thanks a lot,

the switch its available, but its does nothing and its a switch without a state. 

The acs key is still available as a sensor. Maybe this can cause issues?

**Comment by syssi** [comment]
Wait a second. I've an idea whats missing.

**Comment by syssi** [comment]
I've fixed the issue. Please try version `0.7.1`.

**Comment by kolossboss** [comment]
Its working now!! 

Thanks a lot!
