### ISSUE TITLE
Should the eto sensor not be of type total instead of measurement?

### ISSUE THREAD

**Issue by nilrog** [syssi/homeassistant-goecharger-mqtt#36]
I tried to add the **`sensor.go_echarger_xxxxxx_eto`** to the energy dashboard in HA. But then it complained that since it is of type **measurement** it is missing the **last_reset** attribute. But since this is a value that will increase over time, showing the accumulated energy, should it not be of type **total**, or **total_increasing**, instead?

https://developers.home-assistant.io/docs/core/entity/sensor/

**Comment by syssi** [comment]
Good catch! I will update the sensor description to be energy dashboard compatible!

**Comment by syssi** [comment]
Could you double check the unit/precision of the `eto` sensor is correct already? My charger isn't in use yet and the counter shows zero.

**Comment by syssi** [comment]
This is the reason why I'm asking:

```
         native_unit_of_measurement=ENERGY_WATT_HOUR,  # @FIXME: 120 means 12 kWh probably
```

**Comment by nilrog** [comment]
@syssi please do not close tickets immediately before verifying if you have actually released the changes...or give the person who wrote the ticket a chance to respond...

The commit you made to change the sensor type is not part of the latest release you have made (0.7.1). That is why it still says that the type is **measurement**. Please prepare a new release that includes that commit.

**Comment by syssi** [comment]
Sorry for the possible confusion / rushing things. I will prepare the release now. Feel free to respond in closed issues too. ;-)

**Comment by syssi** [comment]
Please keep in mind this hint (https://github.com/syssi/homeassistant-goecharger-mqtt/issues/36#issuecomment-1058306719) after updating to `0.8.0`. I've verified the change at a fresh Home Assistant core install. The sensor is created properly using the `state_class: total_increasing` at new setups. In your case the new code won't by applied automatically (IMO). You have to change the `state_class` manually (once).

**Comment by nilrog** [comment]
Thanks for the new release. It works fine without manually setting the state_class.
