### ISSUE TITLE
Verify the unit of measurement of the `eto` sensor

### ISSUE THREAD

**Issue by syssi** [syssi/homeassistant-goecharger-mqtt#37]
Could somebody do me a favor? Please check the `total energy` at your go-e app and compare the value with the `eto` sensor in Home Assistant. Could you provide both values? I assume something like this:

```
# go-echarger value: 10 kW
# eto sensor value: 100 kW
```

@kolossboss @nilrog @eicosan

**Comment by eicosan** [comment]
Hi syssi!

eto in HAAS: 1559269 **Wh** 
Total from go-e app: 1559,3 **kWh** 

Hope that helps!!
eicosan

**Comment by nilrog** [comment]
As is documented in the [go-echarger API](https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md) the `eto` unit is **Wh**, and the app displays **kWh**.

**Comment by nilrog** [comment]
A possible feature would be to add support for the user to specify if energy sensors should report Wh or kWh when setting up this integration,

**Comment by syssi** [comment]
Indeed. It looks like everything is fine. Thanks for your support. I will prepare a new release now supporting the energy dashboard.
