### ISSUE TITLE
All entities in state Unavailable

### ISSUE THREAD

**Issue by kgroshert** [syssi/homeassistant-goecharger-mqtt#40]
Got a go-eCharger with firmware 041.0 and MQTT connected.
mosquitto_sub shows that status-data is posted by the charger:

go-eCharger/012345/status {"version":"B","tme":"0703221448","rbc":"16","rbt":"7580066","car":"1","amp":"16","err":"0","ast":"0","alw":"1","stp":"0","cbl":"32"...

Alle 98 entities generated by the integration are unavailable or disabled.

The MQTT server (HAs own Mosquitto) uses username/password. Could that be the problem?

**Comment by syssi** [comment]
The root cause is the API version of your device (`v1`). This custom component supports `v2` only.

Duplicate #22

**Comment by kgroshert** [comment]
Ah, just read at https://github.com/goecharger that hardware v2 only supports API v1. Too bad. So I'll stick with the v1-restapi-integration for now. Thanks!

**Comment by syssi** [comment]
I would like to ping you as soon as a first draft of the API v1 implementation is ready. Do you agree?
