### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by GSVSenseAmidMadness** [syssi/homeassistant-goecharger-mqtt#49]
With Home assistant core 2202.8 and 8.1, integration does not start. Receiving the following error: 

"Logger: homeassistant.config_entries
Source: config_entries.py:338
First occurred: 14:16:59 (1 occurrences)
Last logged: 14:16:59

Error importing platform config_flow from integration goecharger_mqtt to set up goecharger_mqtt configuration entry: cannot import name 'MqttServiceInfo' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)"

Home Assistant 2022.8.1
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by syssi** [comment]
Please update this custom component to version `0.12.0`. This should solve the issue.

**Comment by GSVSenseAmidMadness** [comment]
Thank you, issue solved. Did not realize the update was available in HACS.
