### ISSUE TITLE
Stops working on HA core 2022.10.4

### ISSUE THREAD

**Issue by kolossboss** [syssi/homeassistant-goecharger-mqtt#53]
Hi,
not sure whats wrong with 2022.10.4, but this integration stops working. I went back to 2022.10.3 and its working again.
The Go-e charger is on v54.7 but I tried v054.3 and its also not working on 2022.10.4.

Anyone else have this issue?

**Comment by syssi** [comment]
I assume this is the root-cause: https://github.com/syssi/homeassistant-goecharger-mqtt/issues/52

I haven't had the time to solve the breaking change yet.

**Comment by syssi** [comment]
Hmm... I looks like my first assumption is wrong. May be this change is the root cause: https://github.com/home-assistant/core/pull/79421

**Comment by syssi** [comment]
I've prepare a fresh HA core 2022.10.4 install and added the custom component. I don't see any issues / I'm unable to reproduce the issue:

![l1-voltage](https://user-images.githubusercontent.com/2735933/196043933-22228c6f-a692-4d04-b89b-28453e28c921.png)

Could you try to subscribe to your MQTT broker manually and make sure there is incoming traffic on the topics of the charger?

**Comment by SteffenLav** [comment]
Latest core and component works like wonders here too 👍🏻

**Comment by kolossboss** [comment]
Thats strange. 
I updated again to 2022.10.4 and it stops working. 
Then I restarted the Mosquitto Broker and the Integration works again. Even after a HA core restart.
I think I can close this. 
Thanks a lot.
