### ISSUE TITLE
Unavailable Sensors

### ISSUE THREAD

**Issue by Vagabond80** [syssi/homeassistant-goecharger-mqtt#61]
I saw that some people already had the same symptoms, but none of their solutions could help me so far.
![image](https://user-images.githubusercontent.com/102099720/210108219-8a1d1e0b-afde-476d-baba-e30c608338dd.png)
all the Read-only entities show unavailable. I use the MQTT addon on HA and when I connect to it I can see the topics coming in fine. All the shellies I use also work fine through MQTT. 
![image](https://user-images.githubusercontent.com/102099720/210108350-82f36f39-cac1-456e-87c0-a3760685e7d3.png)
When I listen to the topic through the MQTT broker integration I can also see the messages coming in.
![image](https://user-images.githubusercontent.com/102099720/210108616-623e6941-046d-47e3-bc62-17ef1161a0e8.png)
Firmware version of the charger is 0.54.11

**Comment by ReverseEngineeringDE** [comment]
I can confirm this problem. I also can listen to the MQTT broker and get all the values. But the integration just shows "Unavailable". Thank you very much.

**Comment by ReverseEngineeringDE** [comment]
Nevermind - found the problem: You need to add the slash in front of the topic to the MQTT settings in the app.

**NOT: go-eCharger/XXXXXX/**

But like that: /go-eCharger/XXXXXX/

![photo_2023-01-01_23-02-48](https://user-images.githubusercontent.com/114569395/210185928-dbbc73a8-3211-4cd8-afb9-dc91ef90c004.jpg)

**Comment by Vagabond80** [comment]
I can confirm, that this solves the issue! good find. Thank you
