### ISSUE TITLE
Change phases and Requested current to high

### ISSUE THREAD

**Issue by fox-on-tour** [syssi/homeassistant-goecharger-mqtt#65]
Hi there,

thank you for the integration - Works reliably so far.
But i have two questions:

1. Is there a way to change the phases from 1 to 3?
2. Why can I increase the slide controller named as "Requested current" which obviously increases/decreases current ampere value to max 32 amps even though my 11kw box can only handle a maximum of 16 amps?

Thank you so far.

Best regards,

fox

**Comment by syssi** [comment]
1. The `switch` entity `force single phases` can be used to switch from 3 phases to 1.
2. The component supports the 22kw version of the device too. It's a bit tricky to ask the device about the supported limits/feature and apply these constraints to the different entities. As an interim solution we could make to type (11kw vs. 22kw) configurable via the config flow. So we can set the limits easily depending on the configuration.
