### ISSUE TITLE
Where can i enter my own exteral MQTT server

### ISSUE THREAD

**Issue by teremok87** [syssi/homeassistant-goecharger-mqtt#72]
I have an MQTT server under Proxmox running. I can see the go-eCharger topic there, witch has all info.
How can i link your integration to my MQTT server?

Thanks!!

**Comment by syssi** [comment]
Do you use Home Assistant already?

**Comment by teremok87** [comment]
Yes, i started couple of weeks ago. I integrated some inverter, homematic dvices und smart meters. mod bus stuff.

till now i dont have any stuff with mqtt in home assistant. but i installed mqtt integration and specified my mqtt server.

i have hacs running and installed over it your integration. i see a lot of entities but they are not available, greyed out.
i dont see any errors in the log.

**Comment by syssi** [comment]
I assume you hit bug #67 otherwise it should work out of the box. Could you try to change the topic?

**Comment by syssi** [comment]
Which firmware version do you use?

**Comment by teremok87** [comment]
Now it's working. I deleted the cards and pressed the button "add to dashboard" from device menu. I think it was some copy and paste error. Thanks for the quick support!!! :)

**Comment by Gartenkraftwerk** [comment]
Thanks for this hint!

I've done a complete fresh installation of Home Assistant Core on a Pi400 with Raspberry OS. 

What I exactly did now: I changed the Prefix in the go-e charger mobile app from `go-eCharger/xxxxxx/` to `/go-eCharger/xxxxxx/` where `xxxxxx` is my serial number.
