### ISSUE TITLE
Restart of goecharger not possible

### ISSUE THREAD

**Issue by domerich** [syssi/homeassistant-goecharger-mqtt#78]
Hi guys, is there any service to restart the wallbox? In the app I can restart it.
Often the box will only charge the car after I restart it for whatever reason so I want to make an automation if the car is not charging under certrain conditions when it should, restart the box. 

Thanks

**Comment by domerich** [comment]
> There is a button entity called `restart device`. It will issue the MQTT command `rst` and should reboot the charger:
> 
> https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md

hello, this entity is not shown to me ... here are the entities I can see
https://paste.ofcode.org/N5RUqYZaf9Y7H6iZLqF6si

Also I cannot run the assistant because it let's me add only one wallbox so I configured them manually in the configuration.yaml

**Comment by syssi** [comment]
Please go to `Settings` -> `Devices & Services` -> `Devices` -> Search & open the "go-eCharger XXXX device. Please check the "Configuration" tile. It should show the `restart device` button entity:

![device](https://user-images.githubusercontent.com/2735933/221881649-3fe9e48f-6652-4bd5-9ec7-fa51cc90478c.png)

If not please check the "entities not shown" list.

**Comment by syssi** [comment]
Are you sure you are using this custom component!? :-)

**Comment by domerich** [comment]
I'm not sure what I'm using it looks like this
https://www.linkpicture.com/q/2023-02-28_15h27_03.png

**Comment by syssi** [comment]
This is the one you are using. :-P

https://github.com/cathiele/homeassistant-goecharger
