### ISSUE TITLE
psm key issue

### ISSUE THREAD

**Issue by nilrog** [syssi/homeassistant-goecharger-mqtt#89]
In your docs you specify that `psm` is `Configured phases`, and it has been working fine to tell if the charger was set to 1- or 3-phases. I use that to automate how long I need to charge the car to reach a certain level.

But yesterday I updated the charger firmware to the new 0.55.5-beta to play a bit with the new PV stuff, and I also set the charger to the new "Automatic phase switch". And today I noticed that my car charging automation was broken. And when I look at the [go-eCharger API](https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md) it describes `psm` as `phaseSwitchMode (Auto=0, Force_1=1, Force_3=2)`. So instead of being only 1 or 3, as it apparently was before, it can now also be 0...and it can never be 3 as that will be 2. But still, if you set the charger to 3 it still reports 3. So it looks like the new valid values are 0, 1, 3, and their API description is not correct.

Anyway,  this key can no longer be used to check how many phases the charger is set to.

Looking further at the API it seems like the key I am interested in is `pnp` which is only described as `numberOfPhases`. But this key does not seem to be exposed by your integration. So could you please expose the `pnp` key?

**Comment by nilrog** [comment]
I did a bit more checking since it sounded weird that `psm` could be 3, and I see that it is this integration that is remapping the value from 2 -> 3
https://github.com/syssi/homeassistant-goecharger-mqtt/blob/6c0c8a88fca46a19663ac0b0a180c0e681f2e1db/custom_components/goecharger_mqtt/definitions/sensor.py#L44

Anyway, the `psm` key will no longer be possible to use to check how many phases that the charger is using since it can also be 0.

It also looks like the charger is not publishing `pnp` yet, at least not when `psm` is set to 2, when I am sniffing the mqtt traffic. I have not yet checked if it is published only when the actual phase change is done. But it could also be that this is not yet in place. I will try to follow up on that.

**Comment by syssi** [comment]
Fixed by https://github.com/syssi/homeassistant-goecharger-mqtt/commit/3481dfad70de385861a7cc69fd4d450713e51c44
