### ISSUE TITLE
Map psm key on a select entity

### ISSUE THREAD

**Issue by FransOv** [syssi/homeassistant-goecharger-mqtt#97]
The psm key is a three state entity. It is better mapped on to a select entity then to a switch entity. This would also mirror the way this is set in the app.
I suggest something like:
    GoEChargerSelectEntityDescription(
        key="psm",
        name="Force phase selection",
        legacy_options={
            "0": "Automatic",
            "1": "Single phase",
            "2": "Three phase",
        },
        attribute="frc",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        icon="mdi:auto-fix",
        entity_registry_enabled_default=True,
        disabled=False,
    ),

**Comment by syssi** [comment]
This select entity should be available already. I've pushed something like this recently.

**Comment by syssi** [comment]
cp. https://github.com/syssi/homeassistant-goecharger-mqtt/commit/3481dfad70de385861a7cc69fd4d450713e51c44

**Comment by FransOv** [comment]
Strange, I updated to version 0.18.1 and just did a reload in HACS. I can see the select entity here on github, but the downloaded file in my custom components directory is seemingly an older version.

**Comment by syssi** [comment]
The feature isn't released yet and will be part of 0.19.0.

**Comment by syssi** [comment]
The feature is available via HACS now.
