### ISSUE TITLE
Please keep ama as a number entity

### ISSUE THREAD

**Issue by FransOv** [syssi/homeassistant-goecharger-mqtt#98]
Could you please keep ama as a number entity. So we can still set it from HA.
Go-e seems to have mitigated the issue of flash memory wear. See https://github.com/goecharger/go-eCharger-API-v2/issues/112#issuecomment-1375687138

**Comment by syssi** [comment]
It looks like `ama` isn't available as number entity yet. Should we introduce the entity?

**Comment by FransOv** [comment]
Yes please.
